language: c

install:
 - sudo apt-get update
 - sudo apt-get install build-essential cmake libglew-dev xorg-dev python-pip
 - sudo apt-get build-dep glfw
 - sudo apt-get install binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686

 # Ubuntu 12.04 doesn't have a FindGLEW CMake module
 - sudo mv build/FindGLEW.cmake /usr/share/cmake-2.8/Modules/FindGLEW.cmake

script:

 # Build for Linux (our dev platform)
 - ./package/compile-linux

 # Make installation packages for Linux
 - ./package/make-packages

 # Cross compile for Windows
 - ./package/cross-compile-windows

 # Upload packages to bintray
 - ./package/bintray
