---

sudo: required
dist: trusty
language: cpp
services:
  - docker

git:
  submodules: false

matrix:
  allow_failures:
    - os: linux
      env: MAKE_COMMAND="docs upload-docs"
  include:
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: MAKE_COMMAND="osx"
    - os: linux
      compiler: gcc
      env: MAKE_COMMAND="linux tar deb rpm upload-tar upload-deb"
    - os: linux
      env: MAKE_COMMAND="windows zip upload-zip"
    - os: linux
      env: MAKE_COMMAND="docs upload-docs"

before_install:
  - git submodule update --init --recursive
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo pip install awscli
    fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e075a4f5a37b0c115fa8
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always

script:
  - make $MAKE_COMMAND -C package
